### ISSUE TITLE
Feedback on verify_output

### ISSUE THREAD

**Issue by jcheng5** [r-lib/testthat#1017]
## Feedback on verify_output

First, I have to say that even with the following obstacles, this was SO much better than not having snapshot-based testing. I was able to pull out dozens of lines of tedious and fragile rote test code and replace with a single `snapshot(obj)` (that's what I called my [helper function](https://github.com/rich-iannone/blastula/blob/c2b618fd8120ece8efb0e8905dbe870b66b8e657/tests/testthat/helpers-snapshot.R)), over and over.

That said, here are the things I noticed after a couple of hours of use.

1. **The automatically-overwriting-the-snapshot behavior feels like a bad tradeoff to me.** Say the golden snapshot is correct and your new code has introduced a bug that the snapshot test has caught. You'd want to be able to keep changing your code and rerunning the tests until the snapshots pass. Instead, after each failed run, the incorrect snapshot has now become the golden. You have to remember to git revert before each subsequent run. More dangerously, say you _are_ expecting the snapshot to change, as you iteratively modify your code. Once you get to a good-but-intermediate state, you have to be careful to stage the changes in your working copy into your git index, otherwise it'll be very easy to overlook when you've diverged from that intermediate state!
2. **The need to manually specify a path for the snapshot felt tedious**; I wrote a helper function but convention over configuration would be my preference. Furthermore, if testthat had a known directory dedicated for each test context, after each (passing) run it could identify snapshots that are obsolete. (Jest does this automatically, it's very nice.) As it is, before checking in I have to blow away the snapshot directory and run the tests one more time.
3. Following on the previous two points, I'd like to see a workflow where **_adding new_ and *removing obsolete* snapshots can be done automatically with just a warning, but *updating existing* snapshots requires a low-friction but deliberate user interaction**. Jest has a watch mode that makes this ridiculously easy, you just press the letter "u" in the terminal and all changed snapshots are updated; or "i" and you get to approve snapshots one by one. [See demo](https://jestjs.io/docs/en/snapshot-testing#interactive-snapshot-mode)
4. **The automatic `print()` didn't work well for my use case,** where the thing I'm trying to snapshot normally displays itself in a browser. (It was a blastula email but could equally have been any htmlwidget.) And long strings with embedded newlines didn't diff well, since everything ends up smooshed into one string element; I used `cat()` instead. It's possible my scenario is just different than what `verify_output` was intended for; I'm sure `verify_output` works great for ensuring that your console print behavior is as desired, while I'm trying to ensure the data itself is consistent even if it's weirdly shaped.
5. **On Windows, emitting a string containing "\r\n" would result in a snapshot that would never verify.** I think the in-memory version contains "\r\n", but when the snapshot is read from disk, it's normalized to "\n"? Something like that. In my case, the fact that the string contains "\r\n" and not "\n" is crucial, so I had to resort to [this](https://github.com/rich-iannone/blastula/blob/c2b618fd8120ece8efb0e8905dbe870b66b8e657/tests/testthat/test-integration.R#L77-L85). I'd be happy to come up with a minimal reprex if needed.
6. I don't have a suggestion for how to fix this, but **dealing with nondeterministic output was challenging;** in my case, I was snapshotting MIME-encoded emails, which contain a Date header at the top and UUID-based boundary markers. Fortunately in my case it was straightforward to use a hardcoded date in my test, and add a level of indirection to the UUID-generation logic so I could use deterministic values. If I had not been able to do that, I would've wanted to maybe post-process the snapshot output to gsub out the problematic areas.

Thanks for this feature, I'll be using it regardless!

**Comment by hadley** [comment]
Thoughts collated from slack chat:

One simple approach testthat could use: instead of overwriting (e.g.) `test.txt`, save to `name.txt.new` (then delete if they turn out to be the same). Then `verify_accept("test")` would replace `test.txt` with `test.txt.new`. Could have other helpers `verify_reject()` and `verify_diff()`.

**Comment by jcheng5** [comment]
Oh, one more important issue: I could not get this working with `devtools::check()`. It worked using `devtools::test()`. It worked running `R CMD build` and then `R CMD check package_version.tar.gz` from the command line.

But RStudio's "Build | Check" button, and running `devtools::check()` at the console, both consistently gave the following:

```
E  Running 'testthat.R' (3s)
   Running the tests in 'tests/testthat.R' failed.
   Last 13 lines of output:
     cannot open the connection
     Backtrace:
      1. blastula:::snapshot(eml_raw, print = cat)
      2. testthat::verify_output(...) C:\Users\jcheng\Development\blastula.Rcheck\tests\testthat\helpers-snapshot.R:25:4
      3. testthat:::compare_file(path, output, update = TRUE)
      4. testthat:::read_lines(path)
      5. base::readLines(path, n = n, encoding = encoding, warn = FALSE)
      6. base::file(con, "r")
```

OS: Windows 10
R: 3.6.1
testthat: 2.3.2
devtools: 2.3.0

**Comment by hadley** [comment]
1. 3rd edition seems like an opportunity to revisit this behaviour. Oh hmmm, except that won't work because 2. means that you don't want `path` to be the first argument.  

2. Interesting idea — I assume that it just hashes the code. That would also resolve another slightly annoying problem with `verify_output()`; currently if you change the code, you'll get a spurious test failure, when really it should silently regenerate (since there's no golden output)

3. See 1 and https://github.com/r-lib/testthat/issues/1017#issuecomment-616746970

4. I also use `cat()` fairly regularly. To me, the primary advantage of relying on `print()`, is that it gives very similar behaviour to Rmd, which R users are already familiar with. But maybe there's room for another variant that defaults to `cat()` rather than `print()`? Or an argument?

5. Now tracking at #1048. If you have a reprex handy, I'd appreciate it, but I've hit this too, so it shouldn't be too hard for me to replicate.

6. It would be simple enough to add a postprocess argument to `verify_output()` where you could do some `gsub`ing. But is that a significant improvement over post-processing each output by hand?

**Comment by hadley** [comment]
More ideas:

* Add `test_print()` generic that calls `print()` by default, but allows you to customise textual representation specifically for diffs

* If we have high granularity `expect_snapshot()`; when run interactively it would just print out the value since it doesn't have enough context to determine the filename automatically.

**Comment by hadley** [comment]
`expect_snapshot()` needs to be able to capture other side effects, e.g. `expect_snapshot(code, error = FALSE, message = FALSE, warning = FALSE, output = FALSE, print = TRUE)`.

**Comment by hadley** [comment]
Now in #1056 and #1057.

I think the non-determinstic output could be handled with `snapshot_print()` generic; you'd just ensure the output had an appropriate class and then apply regexp munging as needed.
