### ISSUE TITLE
Add support for file-scoped test fixtures

### ISSUE THREAD

**Issue by hadley** [r-lib/testthat#1021]
To replace `setup()` and `teardown()` functions.  Would probably need to build around `defer()`, adding some new file level handler that testthat would be in charge of initialising and destroying.

**Comment by jennybc** [comment]
Depending on how this gets implemented, it would also be interesting to think about how to run file-specific setup during development.

Sometimes you create some nontrivial object that gets used in multiple tests. And you're way down in the file, writing a new test or tinkering with an existing one. And your early attempts fail, presumably because you've forgotten to look for file-specific setup and pre-execute it.

I also like the fact that this proposal would _do_ file-specific teardown in the first place. Currently most testthat users indulge in a little file-specific setup from time to time, but then just let all that stuff accumulate.

**Comment by hadley** [comment]
I just realised that calling a `local_` function at the file level will already do this 😐

**Comment by hadley** [comment]
And we don't want to encourage this sort of behaviour because it makes it hard to diagnose individual tests — you have to remember to run the code at the start of the file first.

**Comment by hadley** [comment]
This also means that `setup()` and `teardown()` are now surplus to requirements.

**Comment by hadley** [comment]
Closing in favour of #1042
