### ISSUE TITLE
Have a `test()` function, similar to `devtools::test()`

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/testthat#1030]
testthat already uses pkgload for package loading, so there is not much benefit using devtools.

**Comment by hadley** [comment]
The primary advantage is that we could just call `testthat::test()` in CI tools.

**Comment by hadley** [comment]
Hmmm, the only place we actually use it is:

```R
maybe_root_dir <- function(path) {
  tryCatch(pkgload::pkg_path(path), error = function(...) path)
}
```

But I think it still makes sense to add this function, since pkgload is a lightweight dependency, and this would be a useful feature.

A few notes from reading `devtools::test()`:

* This function wouldn't save open files or offer to creating testing infrastructure
* Need to set envvar `TESTTHAT_PKG` to name of package
* Most arguments just passed through to `test_dir()`.
* C collation and `useFancyQuotes` should be handled elsewhere in testthat
* Should be able to mostly implement using `test_package_dir()`

What would we call it? Maybe `test_source_package()`?

**Comment by gaborcsardi** [comment]
> What would we call it? Maybe test_source_package()?

`test_local()`, `test_tree()`, `test_package_tree()`?

There is `remotes::install_local()` and `pak::local_*`, FWIW.

**Comment by hadley** [comment]
`test_local()` sounds good to me.

**Comment by hadley** [comment]
If we do this, might as well review all the uses of devtools and replace with pkgload.
