### ISSUE TITLE
`compare(x, y)` causes integer overflow when |x - y| > INT_MAX

### ISSUE THREAD

**Issue by HughParsonage** [r-lib/testthat#1034]
``` r
testthat::compare(.Machine$integer.max, -.Machine$integer.max)
#> Warning in x - y: NAs produced by integer overflow
#> Error in if (!any(diff)) {: missing value where TRUE/FALSE needed
```

<sup>Created on 2020-05-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Probably solvable with 

```r
vector_equal_tol <- function (x, y, tolerance = .Machine$double.eps^0.5) {
  if (is.double(x) || is.double(y)) {
    x_tol_y <- (x == y) | (abs(x - y) < tolerance)
  } else {
    x_tol_y <- (x == y)
  }
  
  (is.na(x) & is.na(y)) | (!is.na(x) & !is.na(y)) &
    (x_tol_y)
}
```

**Comment by hadley** [comment]
This is fixed in waldo:

``` r
waldo::compare(.Machine$integer.max, -.Machine$integer.max)
#> `x`:  2147483647
#> `y`: -2147483647
```

<sup>Created on 2020-06-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

We're moving towards using waldo (see #1027) and I'd prefer not to touch the vector tolerance code in testthat since it's already a bit buggy, and it's easy to unforeseen consequences to cause many packages to fail on CRAN.
