### ISSUE TITLE
Make the `setup-xyz.R` and `teardown-xyz.R` functionality more visible in the documentation

### ISSUE THREAD

**Issue by gavinsimpson** [r-lib/testthat#1046]
The functionality that allows setup and teardown before and after the suite of tests in a package is not clearly document in testthat. I entirely missed this functionality when looking for this feature and even consulted `?teardown` when investigating this for a need in one of my packages. I now appreciate this functionality is mentioned in `?test_dir` but given the presence of `setup()` and `teardown()` I think it would help people discover this feature if it were noted in `?teardown`

Suggest that something like the following be added to `teardown.R`

> Setup or teardown code that performs actions needed for most or all tests, such as the creation of objects used across multiple tests, can be included in files named `tests/testthat/setup-xyz.R` and  `tests/testthat/teardown-xyz.R` respectively. See [testthat::test_dir()] for more information.

I would be happy to prepare a PR to that effect if this was seen as a useful addition to the documentation.

**Comment by hadley** [comment]
In general, we're moving away from setup and teardown files and functions because they make it much harder to debug individual failing tests. I think this was the biggest testing anti-pattern I noticed when fixing dplyr revdeps, so I'd like to beef up the documentation around local test fixtures. (This isn't to say that your use of them is wrong; just that on average I think people are reaching for the wrong tools, and hence making their debugging lives harder.)

OTOH there's no reason not to improve the `teardown()`  docs, even if its use will be de-emphasised in the future. Looking at them with fresh eyes, I'd say that it needs to do a better job of emphasising that `setup()` and `teardown()` have "file" scope, which would lead naturally to a discussion of setup and teardown files that have a "package" scope. 

So a PR would be great 😄

**Comment by doorisajar** [comment]
One potential source of confusion is that `setup` / `teardown` files do NOT get sourced by `test_file`, only `helper` files do (if `load_helpers = TRUE`, which is the default). 

The pattern I use `helpers` for most often, by far, is to check whether my tests are running in a local environment (my laptop) or a cloud environment (CI build runner, cloud compute instance, etc), and skip certain tests based on the result. If I were to put such checks in `setup`, which might seem like a perfectly reasonable thing to do, `test_file` wouldn't work for files that depend on globals I declared in `setup`. 

@gavinsimpson if you do write this documentation PR, it would definitely be worth clarifying this distinction.
