### ISSUE TITLE
Better control over number of workers

### ISSUE THREAD

**Issue by hadley** [r-lib/testthat#1114]
* Parameter? Option?
* Better default detecton

**Comment by hadley** [comment]
Needs to use 2 on CRAN

**Comment by hadley** [comment]
And an option to use one thread per file for debugging.

**Comment by gaborcsardi** [comment]
> And an option to use one thread per file for debugging.

You mean a clean process for each file?

**Comment by hadley** [comment]
@gaborcsardi yeah, that's kind of the same thing right (all though I guess we wouldn't be trying to run them all at the same time)

**Comment by gaborcsardi** [comment]
I think we can implement the env var + option first, and handle the "clean process" feature separately. 

So for the number of processes, how about this logic:

* If `getOption("Ncpus")` is set we use that. This takes care of CRAN.
* If the `TESTTHAT_NCPUS` env var is set, then we use that.
* Otherwise if the machine has `n` logical CPUs, we use `min(n,2)`. I.e. on a single core we still use two processes. This is good for testing parallel testthat, but also makes sense in general, if the testsuite is not cpu heavy.

The `TESTTHAT_NCPUS` env var can be also set in `testthat.R`, if you know that your test suite is not CPU heavy, because e.g. it is I/O heavy.

An alternative to (or in addition to?) the env var we could have a `Config/testthat/ncpus` `DESCRIPTION` entry as well. 

I think for the clean processes we can have a `Config/testthat/...` option, where people can specify a regex for the test files that they want to run in a clean process.

**Comment by gaborcsardi** [comment]
Another idea would be to allow configuring this as the function of the number of processors. Then the test writer can make an informed decision based on how cpu-heavy the tests are. For a cpu heavy test suite it makes sense to set this to the number of processors in the machine. For IO-heavy tests, one CPU can easily run 5 or more test files in parallel. It would be something like this:

```
Config/testthat/ncpus: ncpus * 4
```

or maybe just have a factor on the detected number of cores, defaulting to one:

```
Config/testthat/ncpu-factor: 4
```

**Comment by hadley** [comment]
Maybe `Config/testthat/max-workers`?
