### ISSUE TITLE
should crayon be enabled in 2nd edition?

### ISSUE THREAD

**Issue by gergness** [r-lib/testthat#1136]
The new stuff looks great!

I found one place in my package where the backwards compatibility falls down - in the CRAN version of testthat, crayon printing is enabled, but in the dev even in "2nd edition mode" it is not.

In the CRAN version, both of these tests work, but in dev the first fails. The work around in the second seems reasonable, but figured I'd mention in light of the focus on backwards compatibility.

``` r
library(testthat)

hello <- function() {
    crayon::bgWhite("Hello, world!")
}

test_that("crayon turned off in testthat dev version", {
    expect_equal(hello(), "\033[47mHello, world!\033[49m")
})
#> ── <text>:8:5: failure: crayon turned off in testthat dev version ─────────────────
#> hello() not equal to "\033[47mHello, world!\033[49m".
#> 1/1 mismatches
#> x[1]: "Hello, world!"
#> y[1]: "\033[47mHello, world!\033[49m"

test_that("an okay fix", {
    options(crayon.enabled = TRUE)
    expect_equal(hello(), "\033[47mHello, world!\033[49m")
})
#> Test passed 🥇
```

**Comment by gaborcsardi** [comment]
The CRAN version does not enable crayon AFAICT, it merely leaves its settings and auto-detection untouched. E.g. this is with the CRAN version, in a terminal that does not support colors:

```r
> packageVersion("testthat")
[1] '2.3.2'
> library(testthat)
>
> hello <- function() {
+     crayon::bgWhite("Hello, world!")
+ }
>
> test_that("crayon", {
+     expect_equal(hello(), "\033[47mHello, world!\033[49m")
+ })
Error: Test failed: 'crayon'
* hello() not equal to "\033[47mHello, world!\033[49m".
1/1 mismatches
x[1]: "Hello, world!"
y[1]: "\033[47mHello, world!\033[49m"
> hello()
[1] "Hello, world!"
```

If the dev version turns it off, even for the 2nd edition, that's good, I think, then you can get consistent behavior.

For testing the colors, you can always turn it on using `withr::local_options()`. (A plain `options()` call is not great, because it affects the rest of the test suite, potentially.)

**Comment by hadley** [comment]
@gaborcsardi I think the problem is that the change is likely to cause R CMD check to fail for existing packages, which we don't want (unless it's a very small number of packages).

**Comment by gaborcsardi** [comment]
I _think_ only packages that set up crayon in the `testthat.R` file, or some other way will fail, though. Because if the package relies on crayon's detection only, without explicit config for the tests, then it is broken already.

But In general I don't mind if the reproducible context only applies to the 3rd edition. I think that would make sense.

**Comment by gergness** [comment]
Oh yeah, in making the example minimal, I missed that we were setting the `crayon.enabled` option during setup. So there would be at least one broken dependency (though I can update).

**Comment by gaborcsardi** [comment]
Yeah, I have a couple as well, and relatedly, this trick will not work any more in the 3rd edition:

```r
withr::with_options(
  list(cli.unicode = FALSE),
  test_check("cli")
)

withr::with_options(
  list(cli.unicode = TRUE),
  test_check("cli")
)
```
https://github.com/r-lib/cli/blob/e3ca34656f5bb82df63bfc1c741e75acc79b13d9/tests/testthat.R#L8-L16

Maybe it would make sense to have some option or env var to set the defaults of the standardized context. Otherwise re-running the test suite with different configs will be quite cumversome.
