### ISSUE TITLE
allow callers to 'detect' skips without requiring reporter

### ISSUE THREAD

**Issue by kevinushey** [r-lib/testthat#1154]
Right now, skips are caught and swallowed within a `tryCatch()` handler:

https://github.com/r-lib/testthat/blob/9e643d8ee9772c58d5a6bf0846e16bf78dde59f9/R/test-that.R#L193-L194

However, it'd be useful if that condition could be re-signaled for other entities (other than reporters) which might want to react to that signal. That is, I'd like for the following to work:

```
library(testthat)

skipped <- FALSE
withCallingHandlers(
  test_that("skips can be handled", skip("skip")),
  skip = function(e) skipped <<- TRUE
)

identical(skipped, TRUE)
```

**Comment by kevinushey** [comment]
The simplest solution here (I think) would be to allow that `skip` handler here to re-signal the condition to any other listeners.

**Comment by gaborcsardi** [comment]
I think you can already do this by creating your own reporter, that defines its own `add_results()` method, which can detect skips, and then just call a proper reporter.

**Comment by kevinushey** [comment]
Is there a way to create a new reporter that inherits from the "default" reporter (whatever that might be when tests are run)? Or to get an instance of the 'default' reporter and then monkey-patch its `add_results()` method?

Being able to just "see" skips via `withCallingHandlers()` ultimately seems simpler.

**Comment by gaborcsardi** [comment]
Yeah, e.g. here is a factory that takes a reporter, and then creates a class that inherits from it: https://github.com/r-lib/ps/blob/61fcede3fbbe2f1f124561ec62638550e4226f3e/R/testthat-reporter.R#L74

You can also use `get_reporter()` and then monkey patch the return value.

IMO re-throwing conditions does not seem like a good solution, AFAICT skip conditions are not officially part of the API, so one could argue that they are an implementation detail. This solution also might not work for you when testthat runs the tests in sub-processes, because these conditions will not pass form the sub-process to the main process, even if you re-throw them.

**Comment by kevinushey** [comment]
> This solution also might not work for you when testthat runs the tests in sub-processes, because these conditions will not pass form the sub-process to the main process, even if you re-throw them.

That's a good point I hadn't considered. If it interferes with parallel execution of tests, then I think it's a non-starter.

**Comment by gaborcsardi** [comment]
It does not _interfere_ per se, your PR won't break anything AFAICT, it just won't work, because it will re-throw the skip in the sub-process, and it will not get to the main process. (If you want to catch them in the main process.)

But maybe if you could explain a bit what you want to achieve with detecting the skips, then we could do a better job helping you. :)

**Comment by kevinushey** [comment]
Ultimately, I want a version of the Check reporter that also prints a one-line summary to the console for each test that is run, giving the test name, if it passed, and how long it took. The goal is to have a log in `<package>.Rout` that can easily be scanned from the `.Rout` file generated by `R CMD check`, for checking with e.g. winbuilder output.

**Comment by gaborcsardi** [comment]
The new check reporter does some of this, I think, except that it does not include successful tests and timings. Maybe it should. This is how the output looks: https://github.com/r-lib/testthat/blob/master/tests/testthat/_snaps/reporter-check.md

The check reporter also creates an RDS file now, check if that has the info you need, I think you can download it from win-builder. You can also look at the return value of `test_check()` in `testthat.R`, which has the timing information for every `test_that()` block.

**Comment by lionel-** [comment]
Would it makes sense to resignal conditions from subprocesses in the main process?

**Comment by gaborcsardi** [comment]
The expectation conditions? Just as much sense as re-signalling them in general, I guess. 

But I still don't see the need. What Kevin wants to do is to change the format of the output, and it is best to do that with a new or modified reporter. This is what reporters are for.

**Comment by lionel-** [comment]
Yes I was wondering about resignalling all conditions to the main process.
