### ISSUE TITLE
Feature request: test_examples() with run.dontrun and run.donttest

### ISSUE THREAD

**Issue by msberends** [r-lib/testthat#1182]
Thanks for this package!

I expected the `test_example()` and `test_examples()` functions to have parameters `run.dontrun` and `run.donttest`, just like `utils::example()`.

I agree with what you say in the man page (`?test_examples`):

> Generally, this is redundant with R CMD check, and is not recommended in routine practice.

But as the CRAN maintainers have requested us to decrease the time it takes to run the (nonetheless vey useful) examples, we put some of them in `\donttest{}`. Would be great if we could run them in our `testthat` routine with every git commit.

Or parameters like `only_dontrun` and `only_donttest` would also be tremendously useful IMHO. Could be this be considered?

**Comment by hadley** [comment]
Basically, I regret the decision to add `test_example()` and `test_examples()` to add testthat since I now believe that examples and tests are best kept as separate as possible, and so I'm not planning to add any new features to these functions. I believe that developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄

**Comment by msberends** [comment]
Fair enough, I definitely will!
