### ISSUE TITLE
 "devtools::test()" command fails.  

### ISSUE THREAD

**Issue by maxachis** [r-lib/testthat#1301]
I had previously brought up this issue in #1299. It was recommended that I install the newest version of testthat, and the issue was closed. However, I did have the latest version of testthat, and I have uninstalled and reinstalled the package several times since then--in each case, it is listed as "3.0.1".

This is the error I previously mentioned as receiving. 

> ```
> Loading testthat
> Error in get(genname, envir = envir) : object 'compare' not found
> Error in get(genname, envir = envir) : object 'compare' not found
> Error in get(genname, envir = envir) : object 'testthat_print' not found
> Error in get(genname, envir = envir) : object 'compare' not found
> Testing testthat
> Error: 'test_dir' is not an exported object from 'namespace:testthat'
> ```

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by maxachis** [comment]
It appears I resolved the issue, which was that I was not running the test from a package directory. I think the error was that I was assuming it would run similar to pytest, the Python Unit Testing application I have more direct experience in, and which doesn't require a package structure, at least for the basic devtools::test() command. 

So lesson learned: For the devtools::test(), it must be done from a package directory.
