### ISSUE TITLE
expect_snapshot `json` and `json2` failing for a simple reason

### ISSUE THREAD

**Issue by franzbischoff** [r-lib/testthat#1309]
Hello,

I'm forced to use the option `serialize` (which is not 100% portable) because of this problem on `json`'s:

Both uses `jsonlite` library, and uses the default argument `digits`.

This causes the following problem:

```R
Error (test-windowfunc.R:64:5): mov_sum
Error: Serialization round-trip is not symmetric.

     value         | roundtrip
 [1] 5.7254281461  - 5.7254281500  [1]
 [2] 5.7587528272  - 5.7587528300  [2]
 [3] 5.2088458248  - 5.2088458200  [3]
 [4] 4.1113388848  - 4.1113388800  [4]
 [5] 2.6462555057  - 2.6462555100  [5]
 [6] 0.8732967544  - 0.8732967500  [6]
 [7] -1.0435459914 - -1.0435459900 [7]
 [8] -2.8678391535 - -2.8678391500 [8]
 [9] -4.3692381299 - -4.3692381300 [9]
[10] -5.4659227005 - -5.4659227000 [10]
 ... ...             ...           and 716 more ...
```

This could be fixed using some tolerance, right? :-)

Best regards

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by nlarusstone** [comment]
I have the same issue, here's a simple reprex:

``` r
f <- function() {
  0.900000000000001
}

test_that("Saving/loading json works", {
  expect_snapshot_value(f(), style="json2")
})
#> Error in test_that("Saving/loading json works", Error: Serialization round-trip is not symmetric.
```

<sup>Created on 2021-02-24 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

and test output:

```
Error (test-test.R:6:3): Saving/loading json works
Error: Serialization round-trip is not symmetric.

    `value`: 0.900000000000001
`roundtrip`: 0.900000000000000

i You may need to consider serialization `style`
Backtrace:
 1. testthat::expect_snapshot_value(f(), style = "json2") test-test.R:6:2
 2. testthat:::expect_snapshot_helper(...)
 3. snapshotter$take_snapshot(val, save = save, load = load, ...)
 4. testthat:::check_roundtrip(value, load(save(value)))
 ```

Seems like the issue is that `jsonlite::serializeJSON` has a default argument of truncating to 8 digits (https://github.com/jeroen/jsonlite/blob/master/R/serializeJSON.R), so `load(save(v))` ends up being different from `v` (https://github.com/r-lib/testthat/blob/master/R/snapshot-reporter.R#L68)
