### ISSUE TITLE
Add replace argument to expect_snapshot()

### ISSUE THREAD

**Issue by hadley** [r-lib/testthat#1345]
For when you have sensitive or random components:

```R
  expect_snapshot(
    gargle_oauth_sitrep(tmp_cache)
    replace = c("{path}" = tmp_cache)
  )
```

**Comment by jennybc** [comment]
I ended up needing to do quite a bit of this in gargle, because of temp paths that vary, token hashes that vary by OS or R version, random backoff waiting times, etc.

Observations to guide implementation:

* Sometimes you know the random or sensitive thing in advance (e.g. a temp path you've made and stored and used throughout the test). Then you can get away with `sub(random_thing, replacement, snapshot_content, fixed = TRUE)`, which is nice.
* More often, you need a regular expression. In fact, I often needed look ahead and look behind, so `perl = TRUE` needs to be possible.
* Sometimes you need multiple replacements for 1 snapshot and they could be a mix of fixed string and regex.
* Sometimes you are eliminating a matched expression, i.e. replacing with `""`.

**Comment by jennybc** [comment]
Here's a real example of the basic form I used that also happens to illustrate most of the above:

``` r
out <- capture.output(
    gargle_oauth_sitrep(tmp_cache),
    type = "message"
  )
  out <- sub(tmp_cache, "{path to gargle oauth cache}", out, fixed = TRUE)
  out <- sub("[[:xdigit:]]{7}[.]{3}", "{hash...}", out)
  expect_snapshot(
    writeLines(out)
  )
```

One big bummer about the workaround is that the code in your snapshot ends up being completely uninformative (`writeLines(out)`), so you really have to rely on the test name. It will be much nicer to have this implemented properly in `expect_snapshot()`.

**Comment by hadley** [comment]
I think we'd default to `perl = TRUE`, and if you needed `fixed` for some reason, you'd have to manually escape the regexp (which I don't think should happen very often). 

Could we just disallow replacing with ""? You could always just do `xxxxx` instead?

**Comment by hadley** [comment]
Ooooh I didn't think of that case.

**Comment by hadley** [comment]
May be better to leave completely generic:

```R
expect_snapshot(
  gargle_oauth_sitrep(tmp_cache),
  redact = function(x) {
    x <- sub(tmp_cache, "{path to gargle oauth cache}", x, fixed = TRUE)
    x <- sub("[[:xdigit:]]{7}[.]{3}", "{hash...}", x)
    x
  }
)
```

**Comment by jennybc** [comment]
Here's where things have evolved to in googledrive:

https://github.com/tidyverse/googledrive/blob/6c8f5dd8469689a458ae9d67ad8a359cd293fe25/tests/testthat/helper.R#L35

So I have these two scrubbers and use them in many tests. I can imagine this being a common pattern. So, yes, it would be nice to have a way to apply custom scrubbers inside `expect_snapshot()`.
