### ISSUE TITLE
Automatically attach namespace as a side effect of `skip_if_not_installed()`

### ISSUE THREAD

**Issue by Bisaloo** [r-lib/testthat#1427]
One use case of `skip_if_not_installed()` is to compare an output from the package to the output of a known reference function:

```r
test_that("My custom f() gives the same result as foreignpkg::g()", {

	skip_if_not_installed("foreignpkg")

	expect_equal(f(...), foreignpkg::g(...))
})
```

But in this case, package developers might not want to add foreignpkg to `Suggests` since it is exclusively used a reference in tests. 

And if it is not added to `Suggests`, `R CMD check` will throw a warning because it detects `foreignpkg::` but doesn't see it in `Suggests`.

A good solution would be for `skip_if_not_installed()` to attach foreignpkg's namespace as a side effect (when it is available), thereby removing the need for `::` or `library()`, which are detected by `R CMD check`. I think it makes sense because if users call `skip_if_not_installed("foreignpkg")`, they will surely use functions from foreignpkg right after and we are just removing one step to the process.

For some reason, I am convinced this used to be a feature of `skip_if_not_installed()`, and the exact explanation I gave was in the docs. But I cannot find any trace of this so I must have dreamed it :exploding_head:.

**Comment by hadley** [comment]
I think in this case you _should_ add it suggests, because suggests implies that you need the package for development.

**Comment by Bisaloo** [comment]
Yes, you could probably argue this way and I can understand if that's your final answer.

My position (and that of others according to some discussions I've had) is that this package is not really *needed* for development. It's just a nice bonus minor test. But the package is otherwise thoroughly tested. And packages crucial for proper testing (testthat, withr, possibly others...) are indeed added to `Suggests`. I'm just fine with this test being optional because I don't see it as important enough.

Additionally, I'm a bit reluctant to add this kind of package to `Suggests` because I always feel that adding a package to `Suggests` (or `Depends` or `Imports` for that matters) suggests that you're somehow endorsing it. The situation described in this issue arises precisely when I want to offer an alternative to these package that I don't endorse (because they are not properly documented, tested, etc.). And I don't want to look like I'm advertising them.

**Comment by hadley** [comment]
I think my position is basically: it's better for all packages needed for testing to be declared in one place, and it's not worth managing some hierarchy of "packages that you always need for testing" and "packages that you don't really need but I sometimes useful". And that suggesting a package doesn't imply any endorsement.

I think your position is totally reasonable and internally consistent, it's just different to mine. And I'm leery about making any changes to testthat code because the assumptions we make about suggested packages are deeply woven in to testthat and other packages, and experience has taught us that creating a half-supported workflow is worse than no support at all.
