### ISSUE TITLE
Helper to extract summary of previously run tests?

### ISSUE THREAD

**Issue by njtierney** [r-lib/testthat#1494]
Hi there!

I've got some tests that take a long time to run, and would like to store the test information out at the end, so I can refer to the results of the tests at a later time. Is there a preferred way to set this up to store the test results for later inspection?

**Comment by hadley** [comment]
Is there some reason not to use `saveRDS()` or similar?

**Comment by njtierney** [comment]
Thinking about this further, it would be handy to have an option to save out a plain text report of the test results.

Similar to how R CMD Check gives you a `<pkg-version>.log` file - it would be great if I could save a log file of the test results so I can refer to them later, rather than only looking in the console.

Does that make sense? My thought was perhaps something like:

```r
test(logfile = TRUE)
test(logfile = "path/to/logfile.log")
```

**Comment by hadley** [comment]
I think this is mostly out of scope for testthat, as there are already some features that make it fairly easy to implement yourself. You could set `option(testthat.output_file)` to a path so that the results are saved on disk instead of displayed in the console? You can also do this for a single reporter by setting the `file` argument. If you wanted to both show and save, you could use `MultiReporter` to combine a reporter that displayed interactively, and one that was saved to disk.
