### ISSUE TITLE
expect_warning() not capturing warnings converted from errors (in some cases)

### ISSUE THREAD

**Issue by mkoohafkan** [r-lib/testthat#1711]
Consider these three function that convert an error to a warning in different ways:

```r
# function that throws an error
stopfun = function() {
  stop("I'm an error!")
  invisible(NULL)
}


# functions that convert error to warning

# using tryCatch
fun1 = function() {
  e = tryCatch(stopfun(), error = function(e) warning(e))
  invisible(NULL)
}

# using try() and the full try-error object
fun2 = function() {
  e = try(stopfun(), silent = TRUE)
  if (inherits(e, "try-error")) {
    warning(e)
  }
  invisible(NULL)
}

# using try() and the try-error object's "condition" attribute
fun3 = function() {
  e = try(stopfun(), silent = TRUE)
  if (inherits(e, "try-error")) {
    warning(attr(e, "condition"))
 }
  invisible(NULL)
}


# expectations
expect_warning(fun1())  # does not capture warning!
expect_warning(fun2())  # works as expected
expect_warning(fun3())  # does not capture warning!
```

I'm especially confused as to why `fun2()` works but `fun3()` does not.

**Comment by mkoohafkan** [comment]
The issue seems to be related to the "condition" attribute's `call` element, and specifically if the `call` does not match the parent function:

```r
fun4 = function() {
  e = try(stopfun(), silent = TRUE)
  if (inherits(e, "try-error")) {
    warning(attr(e, "condition")$message)
 }
  invisible(NULL)
}

expect_warning(fun4())  # works as expected
```

But I thought that was the point of `expect_warning()`'s `inherit = TRUE` argument.

**Comment by lionel-** [comment]
That's because you're signalling an error condition with the warning protocol. Neither `tryCatch()` nor `expect_warning()` have any way of detecting the signalling protocol used to emit a condition, they can only detect the class of the condition object.

For this reason the proper way of downgrading an error to warning is to actually create a warning object, which you can do by supplying a message instead of a condition to `warning()`:

```r
tryCatch(stopfun(), error = function(e) warning(conditionMessage(e)))
```
