### ISSUE TITLE
testthat no longer suppresses messages (again)

### ISSUE THREAD

**Issue by tomliptrot** [r-lib/testthat#1746]
This is really a duplicate of  #189. Which was fixed by https://github.com/r-lib/testthat/commit/5ffe62f9441b3e03c801032908479945d4e651df and subsequently closed.

Messages are now getting shown when tests are running. It seems in the past these were suppressed, but this is not longer the case.

```r
library(testthat)

f <- function(x) {
  message("I used to be hidden")
  x
}

test_that("foo", {
  expect_equal(f(1), 1)
})
```

Would it be possible to reinstate their suppression, or at least provide and option to do so?

**Comment by george-hall-ucl** [comment]
Someone who knows more than me can probably better advise; I'm only quickly replying because by chance I was searching for this same problem just now.

I think this behaviour was reverted (i.e. messages were once again displayed) with testthat v3.0: https://testthat.r-lib.org/articles/third-edition.html#messages.

They can be silenced with suppressMessages:

```
test_that("foo", {
  f_out <- suppressMessages(f(1))
  expect_equal(f_out, 1)
})
```

**Comment by hadley** [comment]
This is a deliberate change, see https://testthat.r-lib.org/articles/third-edition.html.

**Comment by stla** [comment]
I don't doubt this is a good choice but let me do a couple of suggestions:

- why not a `skip_messages` function to put at the beginning of a test block ?
- or a "reporter" which silents the messages?

Cheers.
