### ISSUE TITLE
Should `local_edition(3)` also set `local_reproducible_output()`?

### ISSUE THREAD

**Issue by jennybc** [r-lib/testthat#1781]
I'm working in gmailr and haven't turned edition 3 on at the package level. So I'm using `local_edition(3)` in some new tests I'm writing.

I find that snapshot tests contain ANSI escapes if they capture formatted messages.

To prevent that, I'm finding that I need this duo in affected tests:

```
local_edition(3)
local_reproducible_output()
```

Should that be automatic?

**Comment by hadley** [comment]
I think so, so we can do something like this:

```R
local_edition <- function(x, .env = parent.frame()) {
  stopifnot(is_zap(x) || (is.numeric(x) && length(x) == 1))
  old <- edition_set(x)

  # local_reproducible_output() is called automatically by local_test_context()
  # but will be run before local_edition() is called, so we also need to
  # call it here
  if (x >= 3L) {
    local_reproducible_output(.env = .env)
  }

  withr::defer(edition_set(old), envir = .env)
}
```

**Comment by hadley** [comment]
I now think this is not worth fixing — `local_edition()` is used quite a bit internally and calling `local_reproducible_output()` in those places is not desirable because it affects the output of the reporter itself. It's certainly possible to work around that, but I think it'll be easier for you to just use `local_reproducible_output()` where needed.
