### ISSUE TITLE
Specify expected cnd_class in expect_snapshot?

### ISSUE THREAD

**Issue by jonthegeek** [r-lib/testthat#1863]
I've been trying out some (test-first) test-driven development, and one thing that's (mildly) annoying is that snapshots pass my initial test even before the function exists. I can see that it isn't the RIGHT error message in the warning, but it would be nice for the test to fail until the sort of error I'm expecting is thrown. For now I can get by by including `expect_error(..., class = "expected_cls"` in the same test, so it isn't a HUGE issue, but it would be even better if I could pass my specific error class into expect_snapshot, perhaps in the `cnd_class` argument.

I'd be happy to give a PR a try if this sounds worthwhile (and if that PR wouldn't get in the way of fixing the thing with the condition class showing up instead of the call).

**Comment by hadley** [comment]
If you want this level of strictness, I think you should next `expect_error()` inside of `expect_snapshot()`, i.e.

```R
expect_snapshot({
  expect_error(foo(), class = "bar")
})
```

I don't think a `class` argument will work for `expect_snapshot()` because a snapshot might include multiple errors, and then it's hard to reason about how a `class` argument might apply.

**Comment by jonthegeek** [comment]
That makes sense! I didn't realize you could have multiple errors in a single snapshot til this week, so I don't have my head fully wrapped around that yet!
