### ISSUE TITLE
Extract compare() into separate package

### ISSUE THREAD

**Issue by krlmlr** [r-lib/testthat#447]
Suggested name: ddiff ([compare](https://cran.r-project.org/web/packages/compare/vignettes/compare-intro.pdf) is taken; the approach there is nice but individual differences are not printed).

Motivation: testthat used to have detailed information on objects of different lengths (#274) but they are now gone. This is frustrating, perhaps hosting the code in a separate package will avoid such regressions.

**Comment by flying-sheep** [comment]
In #852 i showed what [diffobj](https://cran.r-project.org/web/packages/diffobj/vignettes/diffobj.html) is capable of. We should definitely go for that level of convenience.

**Comment by hadley** [comment]
And make it possible to set which comparison engine is used on a per package basis (#855)

**Comment by coatless** [comment]
Did a separation between testing framework and comparison framework ever materialize in `testthat`?

**Comment by hadley** [comment]
@coatless not yet; if it had this issue would be closed.

**Comment by hadley** [comment]
There are two components to think about:

* A better algorithm for hierarchically comparing two objects. The algorithm needs to stop as high as possible to avoid producing messages that provide an unhelpful level of detail. For example, if the objects have different types, there's no point in descending further. Need to carefully consider how this works with named lists (where diffing the names is useful), and character vectors (where you might want to do compute a Levenshtein difference or similar). This algorithm would power `expect_equivalent()`, `expect_equal()`, and `expect_identical()`. We now have a decent amount of experience writing this sort of algorithm in vctrs and lobstr.

* A better way of displaying the differences between two atomic vectors, so that when the leaves of the tree differ, you can easily see exactly what the difference is. This would be an obvious place to use [diffobj](https://github.com/brodieG/diffobj) since it produces attractive output. This component would be in charge of generating informative failure messages.

Another way of framing the problem comes from this caveat in diffobj:

> diffobj comparisons work best when objects have some similarities, or when they are relatively small.

So the goal of {compare} would be to figure out when the objects or difference are small enough that it's a good idea to use diffobj.

**Comment by flying-sheep** [comment]
Sounds good.

> character vectors […] Levenshtein distance

That’s useful to create a minimal diff, which then should be displayed. I’d like to see the output trying to align the vector elements (and lines per matched element pair):

<pre>
   A                  B
1| foo<del> bar</del> baz        1| foo baz
                      <ins>2|</ins>
2| same               3| same
3| multi<del>!!</del>            4| multi<ins>..</ins>
 | line                | line
</pre>

**Comment by brodieG** [comment]
Some minor comments:

1. you can create arbitrary character representations of your objects (e.g. manifest otherwise invisible elements as text) and use `diffChr` to compare them.
2. `diffPrint` does fallback to `all.equal` if there are non-visible differences, FWIW.
3. `diffobj::ses` is the lightest weight diff interface in the package and might be helpful in determining if an object qualifies for the full decorated diff.  One of the challenges of determining whether two things are good candidates for a diff is that it isn't always trivial to determine that without first running the diff.  The main issue with this is you are responsible for generating the newline delimited character representation to run the diff on, including splitting words out if you want word diffs.  You can set the `max.diffs` parameter to a reasonable number so that it completes quickly (e.g. a diff probably isn't super useful if you have thousands of differences).

**Comment by hadley** [comment]
We also need to track the subsetting operations that lead us to the point of different — i.e. if we have big complicated lists, it would be nicer to able to say that the difference is at `attr(x[[1]]$a, "b")`, and then show the different with diffObj

**Comment by brodieG** [comment]
FWIW, diffobj does try to retain indexing information, as in this example:

```
a <- list(a=matrix(1:27,9), b=list(3, c=list(1, d=matrix(1:15,5), 2)))
b <- a
attr(a[[c(2,2,2)]], 'meta') <- 'neat matrix'
attr(b[[c(2,2,2)]], 'meta') <- 'funky matrix'

diffPrint(a, b)
```
<img width="354" alt="image" src="https://user-images.githubusercontent.com/6105908/68491160-52369180-0218-11ea-8dc1-7fe849928f31.png">

Obviously this is a text representation based heuristic so it doesn't always work, but at least in my experience it works well enough often enough, and even though it doesn't always work it is a huge upgrade over existing test error diagnostic displays.  I guess all this to say if you haven't tried just letting the diff do it's thing try it and see what happens.  @jennybc has some experience I believe with it, so she can give you unbiased input about it if you haven't gotten it already.

If you are concerned about massive diffs there are various settings you can limit the output with.

I'm happy to answer questions in a more interactive environment if you'd like, and will consider FRs to address low hanging fruit that might allay concerns.

**Comment by hadley** [comment]
I would prefer to use diffObj for comparing values, and tackle the comparison of structure myself.  I have no doubt that simply doing a diff of a text representation of an object would be an improvement over the current testthat output, but if I'm going to rewrite the comparison tools, I'd rather do it once with a systematic approach that won't require much further twiddling in the future. 
For example, I want to tackle the "objects are equal but not identical" problem, which arises because the `identical()` and `all.equal()` code paths are different; to me, that feels outside the scope.

**Comment by brodieG** [comment]
No problem, just wanted to make sure you were aware of the existing capabilities.

**Comment by hadley** [comment]
First stab at it: https://github.com/r-lib/waldo

**Comment by brodieG** [comment]
Nice.  FWIW, [`vetr`](https://github.com/brodieG/vetr) also does the recursive object traversal, though with a different type of comparison.  Noting it here in case you end up going down the structure instead of just values comparison path.
