### ISSUE TITLE
encoding on windows with expect_known_output

### ISSUE THREAD

**Issue by tklebel** [r-lib/testthat#694]
I'm having difficulties with `expect_known_output` on windows due to encoding issues. The reference file was created on unix, and tests pass there. On windows several tests fail. I checked the ouput of my functions, it is UTF-8, so there is no reason why a mismatch between output and reference file should occur.

There seems to be a problem in `testthat`, as the following reprex suggests:

```r
library(testthat)

text <- c("Acohido “ Snowden")
file <- tempfile()

expect_known_output(text, file, print = T, update = FALSE)
#> Warning: Creating reference output
expect_known_output(text, file, print = T, update = FALSE)
#> Error: `text` has changed from known value recorded in 'C:\\Users\\...'.
#> 1/1 mismatches
#> x[1]: "[1] \"Acohido “ Snowden\""
#> y[1]: "[1] \"Acohido “ Snowden\""
```

**Comment by gaborcsardi** [comment]
What's your `testthat` version?

**Comment by tklebel** [comment]
2.0.0

**Comment by gaborcsardi** [comment]
Looks like this is a bug indeed. The strings are actually equal, but they have different marked encodings, one is "unknown", the other one "latin2". I don't have an immediate workaround unfortunately, except for using `expect_output`, or `capture.output`.

**Comment by patperry** [comment]
This might be related to a bug in R that is fixed in R-devel: https://github.com/wch/r-source/commit/64f889dd1e5cd472d5869b9a2153061295e135f1 . (`enc2utf8`/`translateCharUTF8` is broken for Windows native strings for characters in CP1252 that aren't Latin-1, like curly quotes.) You can probably use `utf8::as_utf8` to work around this if you need something that works in older versions of R. Alternatively, compare expected output by translating to native encoding, not by translating to UTF-8.

**Comment by gaborcsardi** [comment]
@patperry they don't seem related to me.

**Comment by patperry** [comment]
you know better than I do. any time I see a curly quote and "Windows encoding" I assume it's this CP1252/Latin-1 issue

**Comment by hadley** [comment]
Closing since it seems like this has fixed itself in the mean time.
