### ISSUE TITLE
'Names for current but not for target' error with Test_that

### ISSUE THREAD

**Issue by md0u80c9** [r-lib/testthat#744]
Hi,

I have an integer column in a tibble which I've used as a bitfield (to save having 20 boolean columns).
I have defined the bits using a vector of named integers. These of course may be subject to change in future, and in the case of my real example don't live within the package I'm testing.

The following test in testthat 2.0.0 passes:

```
test_that('Create "names for current but not for target" error', {
  mybitfield = c(Zero = 1,
                 One = 2,
                 Two = 4)
  myResults = c(0,
                mybitfield['Zero'],
                mybitfield['Zero'] + mybitfield['One'])
  expect_equal(myResults, c(0, 1, 3))
})
```

However using named items fails with a create 'names for current but not for target' fails:

```
test_that('Create "names for current but not for target" error', {
  mybitfield = c(Zero = 1,
                 One = 2,
                 Two = 4)
  myResults = c(0,
                mybitfield['Zero'],
                mybitfield['Zero'] + mybitfield['One'])
  expect_equal(myResults,
               c(0,
                 mybitfield['Zero'],
                 mybitfield['Zero'] + mybitfield['One']))
})

```

Is there a workaround for this that doesn't involve hardcoding the values into the test? Clearly my concern is if I change the bitfield later on in the unrelated package the tests will start failing wrongly.

**Comment by vincentvanhees** [comment]
The second code block actually works fine for me, while the first code block fails because myResults is a named num, while c(0,1,3) is not.

Adding as.numeric should address the issue in the first code block:
```
test_that('Create "names for current but not for target" error', {
  mybitfield = c(Zero = 1,
                 One = 2,
                 Two = 4)
  myResults = c(0,
                mybitfield['Zero'],
                mybitfield['Zero'] + mybitfield['One'])
  expect_equal(as.numeric(myResults), c(0, 1, 3))
})

I am also using testthat 2.0.0

```

**Comment by beltorak** [comment]
I've found `dput` extremely useful for printing out the underlying structure of R objects. I'm very new to R myself, but it seems that if expressions are used as the vector components, the vector acquires names.

For 
```
test_that('Create "names for current but not for target" error', {
  mybitfield = c(Zero = 1,
    One = 2,
    Two = 4)
  myResults = c(0,
    mybitfield['Zero'],
    mybitfield['Zero'] + mybitfield['One']
  )

  dput(myResults)
  expected <- c(0, 1, 3)
  dput(expected)
  expect_equal(myResults, expected)
})
```
I get (among the test output)
```
structure(c(0, 1, 3), .Names = c("", "Zero", "Zero"))
c(0, 1, 3)
```

Looking at the help for `c`, there's an optional argument "use.names" that if set to FALSE prevents the vector from acquiring names; e.g.:
```
myResults = c(0,
    mybitfield['Zero'],
    mybitfield['Zero'] + mybitfield['One'],
    use.names = FALSE
)
```
yields
```
c(0, 1, 3)
c(0, 1, 3)
```

Alternately, you can wrap (or magrittr `%>%`) through `as.vector` to strip names; e.g.:
```
myResults = as.vector(c(0,
    mybitfield['Zero'],
    mybitfield['Zero'] + mybitfield['One']
))
```
or
```
myResults = c(0,
    mybitfield['Zero'],
    mybitfield['Zero'] + mybitfield['One']
) %>% as.vector
```
yields the expected `c(0,1,3)`.

I came across this when I was testing a cobbled together class/object with a list (where the list was the expected value). I solved this by piping the actual value/object though a name sorter, since I only create a class to take advantage of overriding the `$` operator, and otherwise don't care that it is an instance of a class. E.g.:
```
value %>% .[order(names(.))] %>% 
    expect_equals(list(f2 = "v2"))
```
I haven't really found a more elegant solution. It might be worth looking into writing a custom expectation.

**Comment by hadley** [comment]
Thanks for the nice analysis @beltorak 

You can also use `mybitfield[['Zero']]` to avoid creating names in the first place.
