### ISSUE TITLE
Zombies in test_check() and devtools::test() for R 3.5.0

### ISSUE THREAD

**Issue by wlandau** [r-lib/testthat#757]
The [`drake`](https://github.com/ropensci/drake) package tries to be a high-performance computing engine, so it includes some small unit tests of its parallel backends. In R 3.5.0, when I run these tests with `test_check()` or `devtools::test()`, I see a bunch of zombie processes when I call `top -bn1 | grep R$` in a Linux shell. Then, when I quit the R session, I see "Error while shutting down parallel: unable to terminate some child processes". This does not seem to happen if I use `devtools::check()` or revert to R 3.4.4.

So far, I have not been able to create a small reprex, so I am not expecting much. I am just writing to ask if there is a difference between `test_check()` and `devtools::check()` when it comes to forked processes. Knowing generalities could help me debug.

I am using development `testthat` (3064e6811dc8c2f2f9dc2f7142781092859f75b6). Session info:

```r
R version 3.5.0 (2018-04-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: KDE neon User Edition 5.12

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.0
```

**Comment by gaborcsardi** [comment]
I think this has nothing to do with testthat but it is most likely an interaction between parallel and callr. They both set up a SIGCHLD  signal handler, and there can only be one active one.

**Comment by wlandau** [comment]
Should I close this issue and post somewhere else, maybe to `callr` or R-devel?

**Comment by gaborcsardi** [comment]
> So maybe SIGCHLD is not getting cleaned up properly in one or the other?

I am not sure what this means. 

I am not sure why parallel cannot clean up the zombies, maybe it just assumes that a SIGCHLD should arrive for them. But that is a bad assumption, even without processx interfering, because SIGCHLD is throttled (at least on macOS), so you don't necessarily receive a signal for every child.

The thing is, parallel only uses SIGCHLD for fork clusters and fork clusters are broken by design. You just can't call fork(2) without execve(2). So I am not sure if it is worth spending too much time on this.

> Should I close this issue and post somewhere else, maybe to callr or R-devel?

processx, I guess. 

Also, please include a proper session info, because I don't know any of your package versions, and they might matter in this case.

**Comment by wlandau** [comment]
Sure, I will close here, post to `processx`, and include a better `sessionInfo()`.

**Comment by wlandau** [comment]
Confirmed: the problem has nothing to do with `testthat`. The following is sufficient to produce zombies.

```r
for (i in 1:2){
  parallel::mclapply(1:2, sqrt, mc.cores = 2)
  processx::run("ls")
}
```

See https://github.com/r-lib/processx/issues/113 for my `sessionInfo()`.
