### ISSUE TITLE
sys.source2 not found in testthat package

### ISSUE THREAD

**Issue by petacube** [r-lib/testthat#800]
just curious when was this function removed and for what reason? i have a lot of code which uses it and it no longer works

**Comment by cderv** [comment]
I don't think that `sys.source2` was ever an exported function. Non exported function are for internal use only and it is strongly discouraged to rely on them... because you never know what could happen to them. 

It is exactly your issue with `sys.source2`. It was not exported, but as the feature was useful, during a refactoring, the feature has been exported as a function called `source_file` in version 1.0.0 (see [Release Note](https://github.com/r-lib/testthat/releases/tag/v1.0.0) in **Others**). The change was made in b7d21c37bd5b8004add2827be176ead9ce64dc5a some time ago now (2016)

You should modify all you code to use `testthat::source_file` from now on (version > 1.0.0).
