### ISSUE TITLE
Package not available when using R CMD check --as-cran

### ISSUE THREAD

**Issue by tramontini** [r-lib/testthat#810]
Executing the command <code> R CMD check --as-cran </code> an error is throw with the message:

> * checking package dependencies ... ERROR
Package suggested but not available: ‘testthat’

Inside the DESCRIPTION file testthat is in Suggests:

`Suggests: testthat(>= 2.0.0)`

**Comment by jimhester** [comment]
Is testthat actually installed on the system you are running `R CMD check` on?

**Comment by tramontini** [comment]
Yes, it is. At the time of sending to CRAN this error will be considered or it will run in the CRAN environment?

**Comment by jimhester** [comment]
You may want to double check the formatting of your DESCRIPTION file (it may need a space between the package name and version string) and that testthat 2.0.0 is actually installed where you think it is, the error you indicate happens when a Suggested package is not installed in the local package library.

**Comment by SylvainCorlay** [comment]
I am seeing the same issue with `testthat` and no version string:

```
Suggests:
    testthat
```

```
Package suggested but not available: ‘testthat’
```

upon `R CMD check --as-cran`.

**Comment by hadley** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
