### ISSUE TITLE
scoping and test env

### ISSUE THREAD

**Issue by merliseclyde** [r-lib/testthat#815]
The following code runs fine within the console, but when placed inside a test fails to find variables defined within the test_that environment.   (example meant to replicate more complicated code within my package) 

Within R:

` data(Pima.tr, package="MASS")
  library(dplyr)
  Pima.tr = mutate(Pima.tr,
                   Z = Pima.tr$age* Pima.tr$bp*5 + rnorm(nrow(Pima.tr)))
  pima_lm <-  lm(Z ~ (age + bp + npreg)^2,
                      data = Pima.tr)

  lm(eval(pima_lm$call$formula),
     data=eval(pima_lm$call$data, parent.frame()))
`

runs with no problem, but adding within a test

`test_that("LM and env", {
  data(Pima.tr, package="MASS")
  library(dplyr)
  Pima.tr = mutate(Pima.tr,
                   Z = Pima.tr$age* Pima.tr$bp*5 + rnorm(nrow(Pima.tr)))
  pima_lm <-  lm(Z ~ (age + bp + npreg)^2,
                      data = Pima.tr)

  lm(eval(pima_lm$call$formula),
       data=eval(pima_lm$call$data, parent.frame()))
})
`

has an error that it cannot find the variable `Z`  even though it is defined within the environment:

Error: Test failed: 'LM and env'   object 'Z' not found
1: lm(eval(pima_lm$call$formula), data = eval(pima_lm$call$data, parent.frame())) at :9
2: eval(mf, parent.frame())
3: eval(mf, parent.frame())
4: stats::model.frame(formula = eval(pima_lm$call$formula), data = eval(pima_lm$call$data, 
       parent.frame()), drop.unused.levels = TRUE)
5: model.frame.default(formula = eval(pima_lm$call$formula), data = eval(pima_lm$call$data, 
       parent.frame()), drop.unused.levels = TRUE)
6: eval(predvars, data, env)
7: eval(predvars, data, env)
> 

I may be misunderstanding how scoping/env works within test that, but expected that code that should work in a clean session should work within test that....

Also data that are loaded in test_that function, remain in global environment

**Comment by hadley** [comment]
That's because (IMO) the way that `lm()` handles environments is not correct.

**Comment by gavinsimpson** [comment]
@hadley What is the right way to handle environments? (I'm seeing the same kind of issue as the OP reports but using a model fitted by `mgcv::gam()` and a data set defined in `setup.R` in my testthat setup can't be found when run with `test()` but the code I'm using works fine otherwise [though clearly not everywhere otherwise testthat won't be generating errors because it can't find data defined in `setup.r`]).

I'm trying to concoct a simple reproducible example but there are quite a few moving parts if I need `setup.R`, `mgcv` and if I'm just doing something wrong by following `lm` et al's NSE I would happily fix that.
