### ISSUE TITLE
Support test skipping on CircleCI builds?

### ISSUE THREAD

**Issue by mbjoseph** [r-lib/testthat#825]
For automated builds running on CircleCI, it might be convenient to have a `skip_on_circle()` function to skip tests, similar to `skip_on_travis()`. By default, CircleCI builds export an environment variable `CIRCLECI` that takes on the value "true": https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables

Is this something that folks would be interested in including in testthat?

**Comment by jimhester** [comment]
Most CI systems set the `CI` environment variable, e.g. both [travis](https://docs.travis-ci.com/user/environment-variables/#default-environment-variables) and [CircleCI](https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables) do.

I think if we were going to add another skip to testthat itself it would be a general`skip_on_ci()` rather than another CI specific skip function.

**Comment by mbjoseph** [comment]
Thanks @jimhester! That does seem like a better solution. 

I have a PR open (https://github.com/r-lib/testthat/pull/826) and would be happy to modify it to implement `skip_on_ci()` if you'd like.

**Comment by jimhester** [comment]
Modifying the existing PR sounds good to me, thanks!

**Comment by mbjoseph** [comment]
Great - I have updated the PR to implement `skip_on_ci()`, which checks to see whether the `CI` environment variable is either `"true"` (as with Travis and CircleCI) or `"True"` (as with AppVeyor Windows builds): https://github.com/r-lib/testthat/pull/826/files#diff-8118c4bf22b8b996a3b1d49ba32e01feR173
