### ISSUE TITLE
`expect_output` can't capture stderr output

### ISSUE THREAD

**Issue by burchill** [r-lib/testthat#843]
I noticed that `expect_output` and `capture_output` can't capture the output of `cat("test", file=stder())`, whereas `capture.output` can (via `type="message"`).  Is this intentional? It feels like the option should exist.

**Comment by hadley** [comment]
This just doesn't seem that important to me. I would consider a PR, but I think you'd need to start by describing a compelling motivation.

**Comment by LeeMendelowitz** [comment]
One compelling motivation is that Shiny Server does not capture stdout into application log files, it only captures stderr. To get around this limitation, I updated an internal package we use to log messages to stderr instead of stdout. But then the package tests fail because `expect_output` does not capture stderr.
