### ISSUE TITLE
expect_equal() fails when compare dispatches to arsenal::compare.data.frame

### ISSUE THREAD

**Issue by euklid321** [r-lib/testthat#848]
Whenever some package happens to load arsenal in the namespace (even without attaching it), testthat::expect_equal does not work with dataframes any more because the compare method dispatches to arsenal::compare.data.frame and testthat::expect_equal cannot handle the return value.

``` r
arsenal::compare(1, 1)
#> Equal
testthat::expect_equal(data.frame(a = 1), data.frame(a = 1))
#> Error in if (x) "success" else "failure": argument is of length zero
```

<sup>Created on 2019-02-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jimhester** [comment]
There is not really anything testthat can do about this, the arsenal package should not register a method for classes when it does not own either the class or the generic. In this case it owns neither...

**Comment by eheinzen** [comment]
arsenal author here.

Jim is right that this is our problem.  We had originally reexported testthat::compare to avoid namespace conflicts (since testthat is a much more popular package than arsenal, but we wanted to use the function name "compare"), but that exact goal has come back to bite us in the rear.  We use a different class name for our object, but naturally that doesn't matter when you call the generic through testthat::expect_equal.

I'll try to think about how best to resolve this.  arsenal:::compare.data.frame may end up needing to get renamed.  Thanks for cross-posting the error on our repo page.

CC eheinzen/arsenal#179

**Comment by eheinzen** [comment]
We're going to rename the function.  Feel free to close this issue.

**Comment by euklid321** [comment]
Thank you!

**Comment by eheinzen** [comment]
For future reference, the function has been renamed in arsenal v3.0.0 (now available on CRAN).  It's now called "comparedf".
