### ISSUE TITLE
Crash with "Error in private$report_event"

### ISSUE THREAD

**Issue by mkurdej** [r-lib/testthat#883]
With versions 2.1.0 and 2.1.1 I get a crash when invoking `devtools::test(reporter = testthat::TeamcityReporter)`:

```
Error in private$report_event("testSuiteFinished", context) :
  argument "context" is missing, with no default
Calls: <Anonymous> ... o_apply -> lapply -> FUN -> <Anonymous> -> <Anonymous>
```

It didn't happen before.
It doesn't depend on R version (it's both with R 3.4 and 3.6), both on FreeBSD and Linux.

**Comment by atheriel** [comment]
I am encountering the same error. Upon further investigation, I have come to believe that it is not a bug in the TeamCity reporter, but a larger issue.

It turns out that the TeamCity reporter is the only existing implementation that actually makes use of the `context` parameter in the `end_context(context)` method. If you patch `testthat::JUnitReporter` or `testthat::SummaryReporter` to use this parameter in any way, you will encounter the same `argument "context" is missing, with no default` error.

I have not been able to isolate the root cause just yet. In the meantime, the following workaround (diff against current `master`) fixes these errors for me:

```diff
diff --git a/R/reporter-teamcity.R b/R/reporter-teamcity.R
index d3ca06e..fbe0fa7 100644
--- a/R/reporter-teamcity.R
+++ b/R/reporter-teamcity.R
@@ -13,12 +13,17 @@ TeamcityReporter <- R6::R6Class("TeamcityReporter",
   inherit = Reporter,
   public = list(
     i = NA_integer_,
+    last_known_cxt = "",

     start_context = function(context) {
+      self$last_known_cxt <- context
       private$report_event("testSuiteStarted", context)
     },

     end_context = function(context) {
+      if (missing(context)) {
+        context <- self$last_known_cxt
+      }
       private$report_event("testSuiteFinished", context)
       self$cat_line()
       self$cat_line()
```

I haven't submitted the above as a PR because I don't really think of it as a "solution". However, I can do so if that makes sense.

**Comment by atheriel** [comment]
Found it: #890.
