### ISSUE TITLE
expect_warning() should have a `class` argument

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/testthat#917]
When we subclass warnings with `rlang::warn()`, I would also expect to be able to do `expect_warning(expr, class = "my_warning")`, so it would be great if that was an argument!

**Comment by hadley** [comment]
Unfortunately this isn't trivial as `expect_warning()` currently captures all warnings and then looks for the match in any of them. I think the exact semantics are difficult to get right so that you're probably better of using `expect_condition()`, `catch_cnd()`, or [`catch_cnds()`](https://github.com/r-lib/rlang/issues/848).
