### ISSUE TITLE
optional praise

### ISSUE THREAD

**Issue by gsee** [r-lib/testthat#92]
Please consider adding an option to allow the user to turn off praise.

**Comment by AdamSpannbauer** [comment]
This is a really old closed issue, but I'd also cast a vote to have optional praise.  It might not be a popular opinion, but... I find the messages like "Your tests are super-duper!" more pandering than encouraging when my tests pass, and I find messages like "Programming is hard!" to be more frustrating than the actual failed test that prompted the message.  This is, of course, a minor thing and can just be ignored, but if there was an easy way to turn off praise, I would.

This could be set at an environment level in `tests/testthat.R` with something like `Sys.setenv("curmudgeon" = TRUE)` or `Sys.setenv("grinch" = TRUE)` so that users not wanting praise are forced to self-reflect while setting the option.

I have implemented this in my fork of the project (using `"grinch"`), but I've held off opening a PR in case it's not a welcome addition.

**Comment by gaborcsardi** [comment]
`tests/testthat.R` is not used when running `devtools::test()`. Also, `tests/testthat.R` usually uses the `check` reporter, which does not praise.

You can actually turn praise off, by running the tests with something like 
```r
devtools::test(reporter = testthat::ProgressReporter$new(show_praise = FALSE))
```
so you could define a shortcut for this.

**Comment by gaborcsardi** [comment]
Also, you lucky this time, but comments on closed issues are _very_ often missed, so consider opening a new issue instead.
