### ISSUE TITLE
Running testthat.R  ERROR

### ISSUE THREAD

**Issue by igordot** [r-lib/testthat#977]
I am running Travis with both release and devel R. On release, everything is fine, but on devel, I get an error:

```
  â”€â”€ 1. Error: (unknown) (@test-functions.R#23)  â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  the condition has length > 1
```

I tried installing the package using my own copy of devel R and everything seems to work, including the test functions. Is this a problem with Travis or testthat? Is there anything I can do to troubleshoot this problem?

**Comment by jimhester** [comment]
The problem is https://travis-ci.org/igordot/clustermole/jobs/632532993#L7303, you are checking if the class is a matrix, but in R devel the class of matrix objects is actually [`c("matrix", "array")`](https://www.mail-archive.com/r-devel@r-project.org/msg41346.html). You should always use either `inherits()` or `is()` to check the classes of objects for this reason.

**Comment by igordot** [comment]
Thank you for checking the code and offering a solution.

Do you know why the tests do not fail on my own copy of devel R?

Also, if I just `class`, it returns just `"matrix"`:

```
> class(matrix(1:6, 2,3))
[1] "matrix"
> sessionInfo()
R Under development (unstable) (2019-12-29 r77627)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
```
